# Generated by Django 2.2.6 on 2019-10-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='average_montly_hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_montly_hours', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='dl_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_model_text', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='last_evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_evaluation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='number_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_project', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='satisfaction_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction_level', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='time_spend_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spend_company', models.CharField(max_length=200)),
            ],
        ),
    ]
