# Generated by Django 2.2.6 on 2019-10-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dl_model',
            name='satisfaction_level',
            field=models.CharField(blank=True, default=1, max_length=200),
        ),
    ]
