# Generated by Django 2.2.6 on 2019-10-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20191006_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='NestleSPF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='average_montly_hours',
        ),
        migrations.DeleteModel(
            name='last_evaluation',
        ),
        migrations.DeleteModel(
            name='number_project',
        ),
        migrations.DeleteModel(
            name='satisfaction_level',
        ),
        migrations.DeleteModel(
            name='time_spend_company',
        ),
    ]
