# Generated by Django 2.2.6 on 2019-12-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20191018_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nestlespf',
            name='file_upload',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
