# Generated by Django 2.2.6 on 2019-12-14 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20191214_1112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NestleSPF',
            new_name='HR_pred',
        ),
    ]
